#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Hello world

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
echo 'Hello World!' | sudo tee  /var/www/html/index.html
#test configuration
sudo nginx -t

service nginx reload
