#!/usr/bin/env bash
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install nginx

echo "Hello Word!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name_;\n\trewrite ^\/redirect_me;"
sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites_enabled/default/

sudo service nginx restart

