#!/usr/bin/env bash
# installs haproxy and configures it
sudo apt -y update
sudo apt -y install haproxy

echo "
frontend web-frontend
   bind *:80
   mode http
   default_backend web-backend

backend web-backend
   mode http
   balance roundrobin
   server 67342-web-01 52.91.135.115:80 check
   server 67342-web-02 54.164.247.169:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod +x /etc/init.d/haproxy
sudo service haproxy restart

