#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for file in *; do   # loop through all files in the current directory
    if [ "${file:0:1}" != "." ] && [ -f "$file" ]; then   # check if the file is not hidden and is a regular file
        filename=${file#*-}   # remove everything before the first dash in the file name
        echo "$filename"   # display the modified file name
    fi
done
